apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
    version: 2022-09-04-57b5965
  name: product
  namespace: dev-mac
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        version: 2022-09-04-57b5965
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: shared-configs
                optional: true
            - configMapRef:
                name: product
                optional: true
            - configMapRef:
                name: product-terraform
                optional: true
            - configMapRef:
                name: shared-secrets
                optional: true
            - secretRef:
                name: product
                optional: true
            - secretRef:
                name: product-terraform
                optional: true
          image: github.com/anddd7/monorepo/product:57b5965-dirty
          name: product
          ports:
            - containerPort: 8080
              name: grpc
