apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: wsl-ubuntu-dev
spec:
  ports:
  - name: grpc-50051
    port: 50051
    targetPort: 50051
  selector:
    app: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
    date: 2022-09-11
    version: v-a7b8b8d
  name: order
  namespace: wsl-ubuntu-dev
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        version: v-a7b8b8d
    spec:
      containers:
      - env:
        - name: PORT
          value: "50051"
        envFrom:
        - configMapRef:
            name: shared-configs-terraform
            optional: true
        - configMapRef:
            name: order
            optional: true
        - configMapRef:
            name: order-terraform
            optional: true
        - configMapRef:
            name: shared-secrets-terraform
            optional: true
        - secretRef:
            name: order
            optional: true
        - secretRef:
            name: order-terraform
            optional: true
        image: github.com/anddd7/monorepo/order:a7b8b8d
        name: order
        ports:
        - containerPort: 50051
          name: grpc
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: order
  namespace: wsl-ubuntu-dev
spec:
  host: order
  subsets:
  - labels:
      version: v-a7b8b8d
    name: v-a7b8b8d
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-grpc
  namespace: wsl-ubuntu-dev
spec:
  gateways:
  - dynamicloading-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /order.InternalService
    route:
    - destination:
        host: order
        subset: v-a7b8b8d
